@tenant_id=1
@access_token={{user_auth.response.body.payload.jwt}}
@refresh_token={{user_auth.response.body.payload.refreshToken}}
@user = {{user_auth.response.body.payload.user}}
@user_id = {{user_auth.response.body.payload.user.id}}
@user_name = {{user_auth.response.body.payload.user.username}}
@user_email = {{user_auth.response.body.payload.user.email}}

### User Authentication
# @name user_auth
curl --location 'https://tenant1.nobious.io:5443/api/ims/user/login' \
--header 'login-type: NATIVE' \
--header 'tenant_id: {{tenant_id}}' \
--header 'Content-Type: application/json' \
--data-raw '{
    "email": "demouser@nobious.com",
    "password": "Nobious2025"
}'


#********************************************************
### Get group/category list
# @name category_list
curl --location --request PUT 'https://tenant1.nobious.io:5443/api/inventory/ticket/getForTypeList' \
--header 'login-type: NATIVE' \
--header 'tenant_id: {{tenant_id}}' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer {{access_token}}' \
--data '{"tenantId": 1, "co": "8", "category": "forType"}'

#*************************************************************
### Get company list:
# @name company_list
curl --location 'https://tenant1.nobious.io:5443/api/vista/company/allcompanies' \
--header 'login-type: NATIVE' \
--header 'tenant_id: {{tenant_id}}' \
--header 'Authorization: Bearer {{access_token}}' \
--data ''

#***************************************************************
### Get locations for a company:
# @name location_list
curl --location 'https://tenant1.nobious.io:5443/api/vista/location/getMultipleCompanieslocations/{{company_list.response.body.cmpDetails.[0].cmpCode}}' \
--header 'login-type: NATIVE' \
--header 'tenant_id: {{tenant_id}}' \
--header 'Authorization: Bearer {{access_token}}' \
--data ''

#*************************************************************
### Get user assigned location by userId:
curl --location https://tenant1.nobious.io:5443/api/ims/user/getUserAssingedLocationByUserId/{{user_id}} \
--header 'login-type: NATIVE' \
--header 'tenant_id: {{tenant_id}}' \
--header 'Authorization: Bearer {{access_token}}' \
--data ''

#**************************************************************
### Get Item list for company and vistaLocation
# @name item_list
curl --location --request PUT 'https://tenant1.nobious.io:5443/api/vista/material/search' \
--header 'login-type: NATIVE' \
--header 'tenant_id: {{tenant_id}}' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer {{access_token}}' \
--data '{"cmp": "{{company_list.response.body.cmpDetails.[0].cmpCode}}", "status": null, "inco": "{{company_list.response.body.cmpDetails.[0].cmpCode}}", "loc": ["{{location_list.response.body.locDetails.[0].loc}}"]}'

#*************************************************************
### Get Item Detail by Vista location
curl --location --request PUT 'https://tenant1.nobious.io:5443/api/vista/material/getItemDetailsByVistaLoc/{{item_list.response.body.itemList.[0].cmp}}/{{item_list.response.body.itemList.[0].item}}' \
--header 'login-type: NATIVE' \
--header 'tenant_id: {{tenant_id}}' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer {{access_token}}' \
--data '["{{location_list.response.body.locDetails.[0].loc}}"]'

#****************************************************************
### Get Item's transaction History
curl --location 'https://tenant1.nobious.io:5443/api/inventory/allocation/allocationHistoryByItem/{{user_id}}/{{item_list.response.body.itemList.[0].cmp}}/{{item_list.response.body.itemList.[0].item}}' \
--header 'login-type: NATIVE' \
--header 'tenant_id: {{tenant_id}}' \
--header 'Authorization: Bearer {{access_token}}' \
--data ''

#****************************************************************
### Get Item Locations with total qty and pallet qty for each location
curl --location --request PUT 'https://tenant1.nobious.io:5443/api/inventory/materialLocation/getMaterialLocationListByItemByAssignedLocation/{{user_id}}' \
--header 'login-type: NATIVE' \
--header 'tenant_id: {{tenant_id}}' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer {{access_token}}' \
--data '{"cmp": "{{item_list.response.body.itemList.[0].cmp}}", "item": "{{item_list.response.body.itemList.[0].item}}", "loc": [{{location_list.response.body.locDetails.[0].loc}}]}'

*****************************************************************